### ISSUE TITLE
Error installing on Linux

### ISSUE THREAD

**Issue by fmrtl73** [portworx/homebrew-brew#1]
vagrant@k2m:~$ brew install pxc
==> Installing pxc from portworx/brew
==> Downloading https://linuxbrew.bintray.com/bottles/go-1.14.4.x86_64_linux.bottle.tar.gz
Already downloaded: /home/vagrant/.cache/Homebrew/downloads/d379718994a9703e4c9ad118cdd0f375ed74b1417adecbac32e429f8c822a387--go-1.14.4.x86_64_linux.bottle.tar.gz
==> Downloading https://github.com/portworx/pxc/archive/v0.29.0.tar.gz
Already downloaded: /home/vagrant/.cache/Homebrew/downloads/c29e7cb81b2c63bb69f12874cfdbbb96dc46ea04ea70ca31c7d7f08c63fb5ed9--pxc-0.29.0.tar.gz
==> Installing dependencies for portworx/brew/pxc: go
==> Installing portworx/brew/pxc dependency: go
==> Pouring go-1.14.4.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/go/1.14.4: 9,441 files, 423.5MB
==> Installing portworx/brew/pxc
==> make VERSION=0.29.0 pxc kubectl-pxc
Last 15 lines from /home/vagrant/.cache/Homebrew/Logs/pxc/01.make:
2020-07-09 15:27:57 +0000

make
VERSION=0.29.0
pxc
kubectl-pxc

/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/make: line 25: exec: : not found

**Comment by fmrtl73** [comment]
vagrant@k2m:~$ brew install --verbose --debug pxc
==> Installing pxc from portworx/brew
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/go.rb
==> Downloading https://github.com/portworx/pxc/archive/v0.29.0.tar.gz
/usr/bin/curl --disable --globoff --show-error --user-agent Linuxbrew/2.4.4\ \(Linux\;\ x86_64\ Ubuntu\ 16.04.5\ LTS\)\ curl/7.47.0 --retry 3 --location --silent --head --request GET https://github.com/portworx/pxc/archive/v0.29.0.tar.gz
Already downloaded: /home/vagrant/.cache/Homebrew/downloads/c29e7cb81b2c63bb69f12874cfdbbb96dc46ea04ea70ca31c7d7f08c63fb5ed9--pxc-0.29.0.tar.gz
==> Verifying c29e7cb81b2c63bb69f12874cfdbbb96dc46ea04ea70ca31c7d7f08c63fb5ed9--pxc-0.29.0.tar.gz checksum
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/go.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gcc.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/binutils.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/make.rb
tar xof /home/vagrant/.cache/Homebrew/downloads/c29e7cb81b2c63bb69f12874cfdbbb96dc46ea04ea70ca31c7d7f08c63fb5ed9--pxc-0.29.0.tar.gz -C /tmp/d20200709-10841-fh62xq
cp -pR /tmp/d20200709-10841-fh62xq/pxc-0.29.0/. /tmp/pxc-20200709-10841-kw0nts/pxc-0.29.0
chmod -Rf +w /tmp/d20200709-10841-fh62xq
==> make VERSION=0.29.0 pxc kubectl-pxc
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/make: line 25: exec: : not found
/usr/bin/curl --version
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/glibc.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/debrew.rb:13:in `raise'
FormulaUnavailableError: No available formula with the name "xorg"
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 2
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/system_config.rb:25:in `formula_linked_version'
NoMethodError: undefined method `linked_version' for nil:NilClass
1. raise
2. backtrace
3. shell
Choose an action: 2
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/system_config.rb:25:in `formula_linked_version'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/system_config.rb:37:in `block in dump_verbose_config'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/system_config.rb:36:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/system_config.rb:36:in `dump_verbose_config'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2025:in `block in system'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1967:in `open'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1967:in `system'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/portworx/homebrew-brew/Formula/pxc.rb:18:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/debrew.rb:24:in `block in install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/debrew.rb:94:in `debrew'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/debrew.rb:24:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb:152:in `block (2 levels) in install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1177:in `block in brew'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2172:in `block (2 levels) in stage'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:474:in `with_env'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2171:in `block in stage'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:111:in `block in unpack'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:197:in `block in mktemp'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:57:in `block in run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:57:in `chdir'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:57:in `run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:196:in `mktemp'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:106:in `unpack'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:81:in `stage'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/forwardable.rb:230:in `stage'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2146:in `stage'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1170:in `brew'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb:123:in `block in install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:474:in `with_env'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb:118:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb:202:in `<main>'
1. raise
2. backtrace
3. shell
Choose an action: 1
==> Kept temporary files
Temporary files retained at /tmp/pxc-20200709-10841-kw0nts
Error: An exception occurred within a child process:
  NoMethodError: undefined method `linked_version' for nil:NilClass
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/system_config.rb:25:in `formula_linked_version'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/system_config.rb:37:in `block in dump_verbose_config'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/system_config.rb:36:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/system_config.rb:36:in `dump_verbose_config'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2025:in `block in system'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1967:in `open'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1967:in `system'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/portworx/homebrew-brew/Formula/pxc.rb:18:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/debrew.rb:24:in `block in install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/debrew.rb:94:in `debrew'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/debrew.rb:24:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb:152:in `block (2 levels) in install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1177:in `block in brew'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2172:in `block (2 levels) in stage'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:474:in `with_env'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2171:in `block in stage'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:111:in `block in unpack'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:197:in `block in mktemp'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:57:in `block in run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:57:in `chdir'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:57:in `run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:196:in `mktemp'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:106:in `unpack'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:81:in `stage'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/forwardable.rb:230:in `stage'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2146:in `stage'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1170:in `brew'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb:123:in `block in install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:474:in `with_env'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb:118:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb:202:in `<main>'

**Comment by lpabon** [comment]
Looks like a bug in homebrew. Try again today. I have tried it on CentOS and Ubuntu and it works.
